language: cpp

os:
  - linux
  - osx

matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx
      osx_image: xcode7.2
    - os: osx
      osx_image: xcode8.1
    - compiler: gcc
      env: COMPILER=g++
    - compiler: gcc
      addons:
          apt:
            sources:
              - ubuntu-toolchain-r-test
            packages:
              - libglib2.0-dev
              - libdbus-glib-1-dev
              - hspell
              - libhunspell-dev
              - libvoikko-dev
              - aspell
              - g++-5
      env: COMPILER=g++-5
    - compiler: gcc
      addons:
          apt:
            sources:
              - ubuntu-toolchain-r-test
            packages:
              - libglib2.0-dev
              - libdbus-glib-1-dev
              - hspell
              - libhunspell-dev
              - libvoikko-dev
              - aspell
              - g++-6
      env: COMPILER=g++-6
addons:
  apt:
    packages:
      - libglib2.0-dev
      - libdbus-glib-1-dev
      - hspell
      - libhunspell-dev
      - libvoikko-dev
      - aspell
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install glib dbus-glib aspell hspell hunspell libvoikko ; fi

script:
  - ./autogen.sh
  - make
  - make check
  - make distcheck
