os: linux
language: cpp
dist: bionic

addons:
  apt:
    sources:
      - sourceline: 'ppa:nuspell/ppa'
    packages:
      - libglib2.0-dev
      - libaspell-dev
      - hspell
      - libhunspell-dev
      - libvoikko-dev
      - voikko-fi
      - aspell-en
      - libunittest++-dev
      - hunspell-fr
      - libnuspell-dev
  homebrew:
  # Note: aspell should work on macOS, but has been removed because one of
  # the tests fails; see https://github.com/Homebrew/homebrew-core/issues/4097
    packages:
      - glib
      - dbus-glib
      - hspell
      - hunspell
      - libvoikko
      - unittest-cpp
    update: true

env:
  global:
    - VERBOSE=1 # Get test logs in Travis logs

jobs:
  include:
    - os: linux
      env:
        - ASAN=yes
    - os: osx

script:
  - ./build-aux/travis-build.sh
