version: "{build}"
clone_folder: c:\projects\enchant

environment:
  global:
    CONFIGURE_FLAGS: --with-hunspell-dir=/mingw64/share/hunspell
    VERBOSE: 1 # Get test logs in output

# FIXME: Build on mingw-w64, mingw-w32 and MSYS2
# matrix:
#   - COMPILER: MinGW-w64
#   - COMPILER: MinGW-w32

init:
  - git config --global core.autocrlf input

install:
  - C:\msys64\usr\bin\bash.exe -l c:/projects/enchant/build-aux/appveyor-install.sh

# FIXME: add all available providers (just aspell?)
build_script:
  - C:\msys64\usr\bin\bash.exe -lc "cd c:/projects/enchant && ./autogen.sh %CONFIGURE_FLAGS% && make && make DISTCHECK_CONFIGURE_FLAGS=\"%CONFIGURE_FLAGS%\" distcheck"
